version: '3.7'

services:
  yarn:
    image: front-end-monorepo_dev:latest
    build:
      context: ./
    entrypoint:
      - "yarn"
    command: ["test:ci"]
  fe-project:
    image: front-end-monorepo_dev:latest
    build:
      context: ./
    entrypoint:
      - "yarn"
      - "workspace"
      - "@zooniverse/fe-project"
    command: ["start"]
    ports:
      - "3000:3000"
  fe-content:
    image: front-end-monorepo_dev:latest
    build:
      context: ./
    entrypoint:
      - "yarn"
      - "workspace"
      - "@zooniverse/fe-content-pages"
    command: ["start"]
    ports:
      - "3001:3000"

